name: Update Documentation
on:
  push:
    branches:
      - "documentation"

jobs:
  export:
    name: Exporting Database
    runs-on: ubuntu-latest
    steps:
      - uses: docker://node:14-alpine
      - uses: actions/checkout@v2

      - name: Installing Modules
        run: npm ci

      - name: Exporting Database
        run: npm run export:templates

      - name: Archiving Database File
        uses: actions/upload-artifact@v2
        with:
          name: database
          path: |
            ./public/database.json
            ./public/images/**

  build:
    name: Building Application
    runs-on: ubuntu-latest
    needs: export
    steps:
      - uses: docker://node:14-alpine
      - uses: actions/checkout@v2

      - name: Installing Modules
        run: npm ci

      - name: Building the Application
        run: npm run build

      - name: Archiving Application
        uses: actions/upload-artifact@v2
        with:
          name: application
          path: ./build/*

  deploy:
    name: "Deploying Application"
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Downloading Application Artifact
        uses: actions/download-artifact@v2
        with:
          name: application
          path: application

      - name: Downloading Database Artifact
        uses: actions/download-artifact@v2
        with:
          name: database
          path: ./application/public/

      - name: Deploying Application to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: documentation
          folder: ./application
          target-folder: ./docs
