name: Update Documentation
on: [push]
  #push:
  #  branches:
  #    - "master"

jobs:
  build:
    name: Building
    runs-on: ubuntu-latest
    steps:
      - uses: docker://node:14-alpine
      - uses: actions/checkout@v2

      - name: Building Application Database
        working-directory: ./docs/templates
        run: |
          npm ci
          node export.js

      - name: Building Application
        working-directory: ./docs/app
        run: |
          cp ../templates/database.json ./src/assets/datasource
          npm ci
          npm run build

      - name: Archiving Application
        uses: actions/upload-artifact@v2
        with:
          name: application
          path: ./docs/app/build/*

  deploy:
    name: "Deploying"
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Downloading Artifact
        uses: actions/download-artifact@v2
        with:
          name: application
          path: application

      - name: Deploying Application to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: documentation
          folder: ./application
