name: Update Documentation
on:
  push:
    paths:
      - "src/**"
      - "dbexport.js"
    branches:
      - "documentation"

jobs:
  build:
    name: Building
    runs-on: ubuntu-latest
    steps:
      - uses: docker://node:14-alpine
      - uses: actions/checkout@v2

      - name: Installing Modules
        run: npm ci

      - name: Building Application Database
        run: npm run export:templates

      - name: Building Application
        working-directory: ./docs/app
        run: |
          pwd
          ls -lrth
          npm run build

      - name: Archiving Application
        uses: actions/upload-artifact@v2
        with:
          name: application
          path: ./build/*

  deploy:
    name: "Deploying"
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: List pwd
        run: ls -lrth

      - name: Downloading Artifact
        uses: actions/download-artifact@v2
        with:
          name: application
          path: application

      - name: Deploying Application to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: documentation
          folder: ./application
          target-folder: ./docs
