name: Update Documentation
on:
  push:
    branches:
      - "documentation"

jobs:
  publish:
    name: Publishing Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: docker://node:14-alpine
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'

      - name: Building Application
        run: |
          npm ci
          npm run build
          cp ./build/index.html ./build/404.html

      - name: Publishing
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: documentation
          folder: ./build
          target-folder: ./docs