name: Update Documentation
on:
  push:
    branches:
      - "documentation"

jobs:
  publish:
    name: Publishing Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: docker://node:18-alpine
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Building Application
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm ci
          npm run build
          cp ./build/index.html ./build/404.html

      - name: Publishing
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: documentation
          folder: ./build
          target-folder: ./docs
