name: Update Documentation
on:
  push:
    branches:
      - "documentation"

jobs:
  publish:
    name: Publishing Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: docker://node:14-alpine
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Installing Modules
        run: npm ci

      - name: Building Application
        run: npm run build

      - name: Publishing
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: documentation
          folder: ./build
          target-folder: ./docs